### ISSUE TITLE
Inject - allow multiple executions

### ISSUE THREAD

**Issue by robertdiers** [opentestingapi/backlog#14]
Give a number of executions for injects, random data must be placed with different values in data pool.
Relevant for counting logic checks.

**Comment by BenjaminGDH** [comment]
> Give a number of executions for injects, random data must be placed with different values in data pool. Relevant for counting logic checks.

@robertdiers I suppose the multiple injects are contributing or belonging to one shared test execution and e.g. the replacement variables from all injects are supposed to be accessible in the later checks, right? Because the cron-attribute already allows to create multiple injects such that each inject is handled as a separate test execution.

**Comment by robertdiers** [comment]
I think we have two different use cases:
* load scenarios
* using injects in chain based on same existing data in random pool for counting based on existing data

**Comment by robertdiers** [comment]
As we create new check chains based on random values, it is not possible to use the same random data pool. In addition having different keys would be really hard to use in checks and giving nearly no value.

**Comment by robertdiers** [comment]
Solved in version 1.35
The injects will open "new chains", so the counter check will be executed multiple times - but that should be fine. Using this approach it is possible to continue doing extra checks and injects within the new chains including unique data creation.
